package main;

import io.TestIoException;

public class Main {

	public static void main(String[] args) /*throws Exception*/ {

//		new TestIo().test(); 
//		new TestIo().test2(); 
//		new TestIoException().testOutput(); 
		new TestIoException().testInput(); 
		
//
//			int[] iArr = new int[10];
//			System.out.println(iArr);
//			System.out.println(iArr[5]);
//		
		
		
		
	}

}
